from django.db import models

class weekly_sheet(models.Model):
    week = models.CharField(max_length=255,primary_key=True)
    week_date=models.DateField(auto_now_add=True)	
    month =models.IntegerField()
    year=models.IntegerField()
    no_of_records=models.CharField(max_length=255)
    sheet_type= models.CharField(max_length=255)


class excel_raw_data(models.Model):
    ct	=models.CharField(max_length=255)
    weekly_sheet= models.ForeignKey(weekly_sheet,on_delete=models.CASCADE)
    affiliate=models.CharField(max_length=255)	
    pid=models.CharField(max_length=255)
    install_partner	=models.CharField(max_length=255)	
    customer_name =models.CharField(max_length=255)	
    sales_rep_name=	models.CharField(max_length=255)	
    kw	=models.FloatField()
    inactive_date= models.DateField(auto_now_add=True)	
    cancel_date=models.DateField(auto_now_add=True)
    approved_date=models.DateField(auto_now_add=True)
    m1_date= models.DateField(auto_now_add=True)
    m2_date=models.DateField(auto_now_add=True)
    state= models.CharField(max_length=255)
    product= models.CharField(max_length=255)
    gross_account_value=models.FloatField(default=00.00)
    epc= models.FloatField()
    net_epc= models.FloatField()
    dealer_fee_percentage =models.FloatField()
    dealer_fee_dollar   = models.FloatField()
    show= models.FloatField()
    redline= models.FloatField()
    total_for_acct = models.FloatField()
    prev_paid= models.FloatField()
    last_date_pd= models.DateField(auto_now_add=True)
    m1_this_week = models.FloatField()
    install_m2_this_week= models.FloatField() 
    prev_deducted = models.FloatField()
    cancel_fee = models.FloatField()
    cancel_deduction= models.CharField(max_length=11)
    lead_cost = models.FloatField(default=1,blank=True,null=True)
    total_in_period= models.FloatField()
    adv_pay_back_amount= models.CharField(max_length=255)
    
