# Generated by Django 4.1.6 on 2023-02-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=30)),
                ('appointment', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('stime', models.TimeField()),
                ('etime', models.TimeField()),
            ],
        ),
    ]
